name = "KMeans in Panel"
description = "An example of how to build a dashboard using Panel."
packages = [
    "https://cdn.holoviz.org/panel/wheels/bokeh-3.5.0-py3-none-any.whl",
    "https://cdn.holoviz.org/panel/wheels/panel-1.5.0b2-py3-none-any.whl",
    "altair",
    "numpy",
    "pandas",
    "scikit-learn"
]
