name = "Simple Panel PyScript Editor Example"
description = "A basic Panel application to be used with the PyScript editor."
packages = [
    "https://cdn.holoviz.org/panel/wheels/bokeh-3.5.0-py3-none-any.whl",
    "https://cdn.holoviz.org/panel/wheels/panel-1.5.0b2-py3-none-any.whl"
]
