name = "dc.js"

packages = ["pandas"]

[files]
"https://raw.githubusercontent.com/dc-js/dc.js/refs/heads/develop/web-src/ndx.csv" = "./ndx.csv"

[js_modules.main]
"https://esm.sh/d3@7.9.0" = "d3"
"https://esm.sh/crossfilter2@1.5.4" = "crossfilter"
"https://esm.sh/dc@4.2.7" = "dc"
